-- ===================================
-- Delete Tables
-- ===================================
DROP TABLE IF EXISTS EmployeeStatistic CASCADE;

DROP TABLE IF EXISTS Sale CASCADE;

DROP TABLE IF EXISTS CarCondition CASCADE;

DROP TABLE IF EXISTS Car CASCADE;

DROP TABLE IF EXISTS Model CASCADE;

DROP TABLE IF EXISTS Client CASCADE;

DROP TABLE IF EXISTS Employee CASCADE;

DROP TABLE IF EXISTS StatusType CASCADE;

DROP TABLE IF EXISTS Position CASCADE;

DROP TABLE IF EXISTS TransmissionType CASCADE;

DROP TABLE IF EXISTS EngineType CASCADE;

DROP TABLE IF EXISTS BodyType CASCADE;

DROP TABLE IF EXISTS ClientType CASCADE;